// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijsydzfmyqbyaahsstoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqc3lkemZteXFieWFhaHNzdG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzA0MTgsImV4cCI6MjA2MzMwNjQxOH0.rCdK5eIml6w84T5opqE7A1AsWnADnT5QsPnLUGwn3Ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);